### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by crutchcorn** [sophos/Sophos-Central-SIEM-Integration#1]
In our organization we have standardized on Python 3 for our codebase. I know Python 3 fairly well and would be willing to make a pull request with a working version of this program in Python 3 (and see if I just can't get it backwards compatable with 2 as well). Is this something that you are able to accept, or is this something I'll have to wait on?

**Comment by keeely** [comment]
Please try this version: https://github.com/keeely/Sophos-Central-SIEM-Integration
