### ISSUE TITLE
REQUEST - Customer Name Field

### ISSUE THREAD

**Issue by arnydo** [sophos/Sophos-Central-SIEM-Integration#14]
Instead of having just the customer id field it would be nice to have the actual customer name come over.
This would help with separating multiple entities when using a SIEM to collect data from multiple customers.

**Comment by taycom** [comment]
Hi, any updated about this requirement !!! Please is very important for implantate with differents customers in one SIEM plattform.

**Comment by rkamat** [comment]
Duplicate of https://github.com/sophos/Sophos-Central-SIEM-Integration/issues/38
