### ISSUE TITLE
No section: 'login'

### ISSUE THREAD

**Issue by dannyhanes** [sophos/Sophos-Central-SIEM-Integration#16]
Downloaded the zip. 
Extracted to downloads folder
Modified `config.ini`
Ran `python siem.py`

CONFIG.INI
```[login]
# API Access URL + Headers
# API token setup steps: https://community.sophos.com/kb/en-us/125169
token_info = url: https://api1.central.sophos.com/gateway, x-api-key: xxXXxxXXXxxXXxxXXXxxxxXXxxXXXxxXXxxXXXxx, Authorization: Basic xxXXxxXXxXxxXXxxXXxXxxXXxxXXxXxxXXxxXXxXxxXXxxXXxXxxXXxxXXxXxxXXxxXXxXxxXXxxXXxXxxXXxxXXxXxxXXxxXXxXxxXXxxXXxXxxXXxxXXxXxxXXxxXXxXxxXXxxXXxXxxXXxxx=

# format can be json, cef or keyvalue
format = json

# filename can be syslog, stdout, any custom filename
filename = result.txt

# endpoint can be event, alert or all
endpoint = event

# syslog properties
# for remote address use <remoteServerIp>:<port>, for e.g. 192.1.2.3:514
# for linux local systems use /dev/log
# for MAC OSX use /var/run/syslog
address = /var/run/syslog
facility = daemon
socktype = udp

```

ERROR: 
```
Traceback (most recent call last):
  File "/Users/username/Downloads/Sophos-Central-SIEM-Integration-master/siem.py", line 476, in <module>
    main()
  File "/Users/username/Downloads/Sophos-Central-SIEM-Integration-master/siem.py", line 153, in main
    token = config.Token(cfg.token_info)
  File "/Users/username/Downloads/Sophos-Central-SIEM-Integration-master/config.py", line 30, in __getattr__
    return self.config.get('login', name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'login'
```

PYTHON VERSION:
```
Python 2.7.10
```

**Comment by keeely** [comment]
It is indeed missing the [login] section identifier.  Please replace that, and make it like the original:
https://github.com/sophos/Sophos-Central-SIEM-Integration/blob/master/config.ini

**Comment by dannyhanes** [comment]
So when I copy and pasted for the error report, I forgot to grab `[login]` at the top. But, my `config.ini` file does have that. The only change I have made is copying and pasting my API Access URL + Headers into `config.ini`

**Comment by keeely** [comment]
Well the python library can't find the section.  I've never seen this error before, so I guess there is something about what you pasted that has messed the file up.   If you can't attach the actual file (I understand why of course) then try something like:

import ConfigParser
config = ConfigParser.ConfigParser()
config.read(“your ini file”)
print config.get('login', “token_info”)

And see what it says (for the original and new file).

**Comment by dannyhanes** [comment]
Hmm looks like something got copied incorrectly. I may try manually typing it out and see what happens. 

```
SyntaxError: Non-ASCII character '\xe2' in file /Users/username/Downloads/Sophos-Central-SIEM-Integration-master 2/test.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by keeely** [comment]
I've always just pasted that token using Chrome on a Mac and never had any issues.  It seems to remove all the newlines correctly.  I'd generally be pasting into Vim, if FWIW.

**Comment by dannyhanes** [comment]
@keeely VIM for the win. Very strange, but it seems to be working now. Thanks!

**Comment by vikrantlw** [comment]
@dannyhanes you may try to execute the siem.py file from other than code folder or executing through cron job.
Error Occurred because you didn't set the  SOPHOS_SIEM_HOME environmental variable and
siem.py -> line 136 
`app_path = os.path.join(os.getcwd())`

kindly change to 
`app_path = os.path.join(os.path.abspath(os.path.dirname(__file__)))
`

because **os.getcwd()** returns current working directory if you run code from home dir with absolute path of the code file
```
$pwd
-> /home/vikrant
```
```
python /usr/src/sophos/code/siem.py
 --> unable to find the config file and cause above error.
```
@jmcgourty kindly correct it.
