### ISSUE TITLE
python siem.py fails wirth "AttributeError: 'NoneType' object has no attribute 'group'"

### ISSUE THREAD

**Issue by DavidRHawley** [sophos/Sophos-Central-SIEM-Integration#20]
Errors when we run the "python siem.py" command:

Traceback (most recent call last):
  File "siem.py", line 476, in <module>
    main()
  File "siem.py", line 153, in main
    token = config.Token(cfg.token_info)
  File "/run/Sophos/config.py", line 38, in __init__
    self.url = m.group("url")
AttributeError: 'NoneType' object has no attribute 'group'

WE have imported the "keys" or tokens from the Sophos Central Console into the config.ini file.

we set the SOPHOS_SIEM_HOME environment variable to point to the folder where config.ini, siem_cef_mapping.txt, siem.py etc are located.

In the ~500 line script there is no method called NoneType and the only time the word group is uses, is in a comment.

How do we fix this issue or run the 'python siem.py" command to get the desired results w/o errors?

Thank You, David

**Comment by keeely** [comment]
You appear to have copied the token incorrectly into config.ini.  Are you sure you copied it all, exactly as it appeared on the console?

**Comment by keeely** [comment]
Also, ensure it's actually finding the config.ini file in the first place, you could try giving explicit path to it on the command-line when you run siem.py?

**Comment by keeely** [comment]
It's been a while, so presumably this is solved.
