### ISSUE TITLE
Different "state_file_name"

### ISSUE THREAD

**Issue by AndreaErrani** [sophos/Sophos-Central-SIEM-Integration#22]
I'm using -c option for using different file .ini for different sophos account.
For each .ini I specify different API access and log file name.

I have a problem: the name of the generated status file is always the same ("siem_lastrun_events.obj")

Is it possible add a variable in the .ini file to configure different "state_file_name"?

**Comment by keeely** [comment]
state_dir can be a relative path, so you could just run siem.py from a different directory for each account.  The state file will have the same name, but it will be in a different place.  Maybe not the nicest solution but it will work.

**Comment by anil-sophos** [comment]
@AndreaErrani In the latest version V.2.0.1, we added configuration to user give state file path by updating state_file_path key. You can use the new latest release code and check.
