### ISSUE TITLE
API return just 100 random endpoints

### ISSUE THREAD

**Issue by saostad** [sophos/Sophos-Central-SIEM-Integration#23]
Hi,
I tried to use api to get list of my endpoint devices but it just gives me random 100 devices every request but it shows me there are 909 device exists! 

> {
    "total": 909,
    "filtered": 909,
    "items": [],
    "next_key": null
}

**Comment by simonp001** [comment]
+1 with this.
When the GET command "/migration-tool/v1/endpoints" is used , if the number of endpoint is >100, the JSON is only 100 objects.
Also, the JSON is corrupted, even though the1st element of the JSON provides the correct value for the total number of endpoints.
I have attached a sample JSON file that is returned for our client MTG that has 201 endpoints in total.

Does the command use pagination – if so, can you explain how it is implemented ?
There does not seem to be any indication of such in the swagger documentation.

**Comment by keeely** [comment]
Please raise this with Sophos support directly.

**Comment by simonp001** [comment]
I have – still waiting for a response.


[Logic-Plus-Pty-Ltd]<https://www.logicplus.com.au/>

Simon Parr
Business Improvement

M +61 430 767 704 | T 08 7127 3000
202 Halifax Street, Adelaide, SA, 5000
logicplus.com.au<https://logicplus.com.au>

**Comment by rkamat** [comment]
That is an internal API endpoint which we use for migrating from our on-premise product to Sophos Central. It isn't a part of the siem.py functionality. Closing this for now.
