### ISSUE TITLE
Sub Estate

### ISSUE THREAD

**Issue by xayleth** [sophos/Sophos-Central-SIEM-Integration#24]
Is there a way to script out multiple API URL's and Tokens if one has sub estates in the same config file?

**Comment by rkamat** [comment]
@xayleth, assuming you are still interested in this issue you raised over 2 years ago now, in the latest version (2.0.1) you can now use organization-level API credentials in the config.ini file. You have to specify which tenant (sub-estate) you want to pull events/alerts for using the "tenant_id" config parameter. In the future, we plan to support running the script in a mode that aggregates alerts and events across tenants in the same organization. Closing this issue for now.
