### ISSUE TITLE
Error trying to run siem.py

### ISSUE THREAD

**Issue by vladimirgluten** [sophos/Sophos-Central-SIEM-Integration#34]
When I run the siem.py, I get the following error.  The name_mapping.py file is in the same folder as siem.py.  Not sure what I'm doing wrong

Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\Sophos-Central-SIEM-Integration-master\siem.py", line 40, in <module>
    import name_mapping
ModuleNotFoundError: No module named 'name_mapping'

**Comment by anil-sophos** [comment]
@vladimirgluten We have updated the siem.py. can you please verify the things with the latest version code?

**Comment by rkamat** [comment]
Closing this for now. Please reopen if this turns out not to be a local environmental issue.
