### ISSUE TITLE
Support python 3

### ISSUE THREAD

**Issue by themrkeys** [sophos/Sophos-Central-SIEM-Integration#35]
Currently describes requires python2 needs to utilize python3 due to EOL

**Comment by kathyn-sm** [comment]
I think the script does support python3 but they should deprecate python2 due to EOL
https://github.com/sophos/Sophos-Central-SIEM-Integration/blob/master/siem.py#L18-L25

**Comment by rkamat** [comment]
Closing this as the latest release 2.0.1 now supports (only) Python 3.6+.
