### ISSUE TITLE
JSON Result File contains empty lines

### ISSUE THREAD

**Issue by matthewtckr** [sophos/Sophos-Central-SIEM-Integration#37]
When using the default settings of logging JSON to a `result.txt` file, there are empty lines between each JSON object

The `u"\n"` should not be appended when serializing each result to JSON
https://github.com/sophos/Sophos-Central-SIEM-Integration/blob/v1.1.0/siem.py#L278

**Comment by rkamat** [comment]
@matthewtckr, is that a problem?

**Comment by matthewtckr** [comment]
We can crybaby close this. I've since switched from an ELK stack where this is a problem

**Comment by rkamat** [comment]
We've fixed this now: https://github.com/sophos/Sophos-Central-SIEM-Integration/pull/59 (in master)
