### ISSUE TITLE
Add Tag for Customer

### ISSUE THREAD

**Issue by taycom** [sophos/Sophos-Central-SIEM-Integration#38]
Is possible add tag for add name of customer in CEF(or another) format in the first of the line? 
This is actually message;
<30>Access was blocked to "www.veterinariotraumatologo.com" because of "Mal∕HTMLGen-A".|CEF:0|Sophos|sophos central|1.0|Event::Endpoint::WebFilteringBlocked|Access was blocked to "www.vetesadfdsao.com" because of "Mal∕HTMLGen-A".|1|sour
And my petition is:
**CUSTOMER_NAME**<30>Access was blocked to "www.veterinariotraumatologo.com" because of "Mal∕HTMLGen-A".|CEF:0|Sophos|sophos central|1.0|Event::Endpoint::WebFilteringBlocked|Access was blocked to "www.vetesadfdsao.com" because of "Mal∕HTMLGen-A".|1|sour
Thanks

**Comment by rkamat** [comment]
We don't plan to fix this for the foreseeable future. However, you a workaround available, in that, you can enumerate your customers using the [Partner API](https://developer.sophos.com/docs/partner-v1/1/routes/tenants/get) or the [Organization API](https://developer.sophos.com/docs/organization-v1/1/routes/tenants/get) operation to enumerate tenants, then post-process the output of this tool to add the customer name.
