### ISSUE TITLE
Break out the TYPE field into TYPE and SUBTYPE

### ISSUE THREAD

**Issue by davidrudduck** [sophos/Sophos-Central-SIEM-Integration#40]
For filtering and reporting it would make life a lot easier if "TYPE" was broken out into "TYPE" and "SUBTYPE".

**Currently:**
{"customer_id": "1111111111111111111111111", "severity": "low", "endpoint_id": "111111111111111111", "endpoint_type": "computer", "source_info": {"ip": "10.80.111.111"}, **"type": "Event::Endpoint::WebControlViolation"**, "id": "111111111111111111", "group": "WEB", "name": "User bypassed category block to 'https://config.edge.skype.com'", "datastream": "event", "duid": "1111111111", "rt": "2020-07-09T19:05:59.696Z", "end": "2020-07-09T19:00:57.000Z", "suser": "Joe User", "dhost": "COMPUTER NAME"}

**Suggestion:**
{"customer_id": "1111111111111111111111111", "severity": "low", "endpoint_id": "111111111111111111", "endpoint_type": "computer", "source_info": {"ip": "10.80.111.111"}, **"type": "Event", "class": "Endpoint", "subtype": "WebControlViolation"**, "id": "111111111111111111", "group": "WEB", "name": "User bypassed category block to 'https://config.edge.skype.com'", "datastream": "event", "duid": "1111111111", "rt": "2020-07-09T19:05:59.696Z", "end": "2020-07-09T19:00:57.000Z", "suser": "Joe User", "dhost": "COMPUTER NAME"}

**Comment by rkamat** [comment]
We have no immediate plans to implement this, mainly because the delimiter `::` in the event type value is not significant. The event type is just a string and should not be expected to be a hierarchical namespaced value. If you really need this, you could post-process the output of siem.py.
