### ISSUE TITLE
Multi-Tenancy Support

### ISSUE THREAD

**Issue by davidrudduck** [sophos/Sophos-Central-SIEM-Integration#41]
Would be advantageous if we could run this script across multiple clients that exist in our Sophos Central Partner Portal and tag the entry with a particular customer / customer ID.

**Comment by rkamat** [comment]
@davidrudduck, thanks for the feedback. With the latest release (2.0.1) you can now use partner/organization level API credentials in the config.ini file. You have to specify which tenant you want to pull events/alerts for using the "tenant_id" config parameter. In the future, we plan to support aggregating this data across tenants managed by a partner or tenants that are part of an organization.
