### ISSUE TITLE
Issue running into RHEAL 7

### ISSUE THREAD

**Issue by kaaltech** [sophos/Sophos-Central-SIEM-Integration#55]
HI,

I am trying to install it on red hat and send it to QRadar. However it is giving me below error.

Sophos state file not found
Traceback (most recent call last):
  File "siem.py", line 404, in <module>
    main()
  File "siem.py", line 401, in main
    run(options, config_data, state_data)
  File "siem.py", line 393, in run
    endpoint, options, config_data, state
  File "siem.py", line 366, in get_alerts_or_events
    api_client_obj = api_client.ApiClient(endpoint, options, config, state)
  File "/root/Sophos-Central-SIEM-Integration/api_client.py", line 68, in __init__
    self.opener = self.create_request_builder()
  File "/root/Sophos-Central-SIEM-Integration/api_client.py", line 94, in create_request_builder
    handler = urlrequest.HTTPSHandler()
AttributeError: module 'urllib.request' has no attribute 'HTTPSHandler'

**Comment by rkamat** [comment]
Hi @kaaltech, please check the minimum version of Python you are using. For v2.x of this tool, you need to use Python 3.6 as a minimum. Thanks

**Comment by kaaltech** [comment]
@rkamat I have python 3.7 on that linux box.

**Comment by rkamat** [comment]
@kaaltech, perhaps your Python distribution is missing openssl support? What do you get if you type `openssl version` in the terminal. Does that match the output of `python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"`?

**Comment by kaaltech** [comment]
@rkamat - It worked, can we make it real time fetching instead of last 24 hours or 12 hours. I am not good with python so asking. It says no new alerts for last 12/24 hours and then it stops. I am fetching logs from there to QRadar and wanted it to run real time.

**Comment by rkamat** [comment]
It won't be realtime, but you can set up a schedule to run the script every 10-15 minutes. It uses the stored state to request only new events. Only in the absence of the stored state does the script fetch the last 24 hours of events.
