### ISSUE TITLE
syslog is not supported on this platform

### ISSUE THREAD

**Issue by arnydo** [sophos/Sophos-Central-SIEM-Integration#6]
Configured output to go to a remote syslog server and returned "syslog is not supported on this platform".
Python 2.7.9 and script is running on a Windows 10 machine.
Output to all other formats work as expected.

Is there an extra step to push to the remote syslog server?

**Comment by keeely** [comment]
Please try this version: https://github.com/keeely/Sophos-Central-SIEM-Integration
