### ISSUE TITLE
Multi Tenant support

### ISSUE THREAD

**Issue by Vetpeet** [sophos/Sophos-Central-SIEM-Integration#62]
Hi Sophos,

Apologies if I have missed how to configure this in the config.ini but it does not appear that it this tool supports multi tenants.

Looking at the config.ini it was not clear how you would handle multi tenant credentials?

**Comment by rkamat** [comment]
Hi @Vetpeet, the tool only supports one tenant at a time (`tenant_id` in config.ini). You can use your partner or organization level API credentials (`client_id` and `client_secret` in the config). You can get the account IDs of your tenants by calling the [Partner API](https://developer.sophos.com/docs/partner-v1/1/routes/tenants/get) if you are a Sophos Partner or the [Organization API](https://developer.sophos.com/docs/organization-v1/1/routes/tenants/get) if you are using enterprise API credentials.

We have an item on our roadmap to support syncing multiple tenants at a time. For now, you will need to work around it by using different config files, one per tenant.
